/***************************************************
  This is a library for the HIP Detection

  Use BLE to send & receive data and command from/to a ble master device
  Control DAC80501 and receive data from ADS1235

  Sheng Wang Dec 2021
 ****************************************************/

#ifndef Detection_BLE_H
#define Detection_BLE_H


#include <ArduinoBLE.h>
#include "ADS1235.h"
#include "DAC80501.h"

inline BLEService DetectionServcie("19B10010-E8F2-537E-4F6C-D104768A1214"); // create service, GUID generated by https://www.guidgenerator.com/online-guid-generator.aspx
// create switch characteristic and allow remote device to read and write
inline BLEByteCharacteristic switchCharacteristic("19B10011-E8F2-537E-4F6C-D104768A1214", BLERead | BLEWrite);
  // BLEDescriptor SwitchDescriptor("2901", "millis");
  // switchCharacteristic.addDescriptor(SwitchDescriptor);
  // Tried to give charactersitc a name, failed. Recognized as 'unknown characteristic'
// create byte characteristic and allow remote device to read and write
inline BLEByteCharacteristic LaserCharacteristic("19B10012-E8F2-537E-4F6C-D104768A1214", BLERead | BLEWrite);
  // BLEDescriptor LaserDescriptor("2902", "Laser");
  // LaserCharacteristic.addDescriptor(LaserDescriptor);
// create byte characteristic and allow remote device to get notifications
inline BLEByteCharacteristic RDATACharacterstic("19B10013-E8F2-537E-4F6C-D104768A1214", BLERead | BLENotify);
  // BLEDescriptor RDATADescriptor("2903", "RDATA");
  // RDATACharacterstic.addDescriptor(RDATADescriptor);

inline void blePeripheralConnectHandler(BLEDevice central);
inline void blePeripheralDisconnectHandler(BLEDevice central);
inline void switchCharacteristicWritten(BLEDevice central, BLECharacteristic characteristic);

class DetectionBLE  {
public: 
  DetectionBLE(ADS1235 & ADC, DAC80501 & DAC): _adc(ADC), _dac(DAC){};
  ~DetectionBLE(){};

public:
int begin();
int read_pct();
// int update();


int write_dac(int ble_dac_tgt);

// void blePeripheralConnectHandler(BLEDevice central);
// void blePeripheralDisconnectHandler(BLEDevice central);

private:
 ADS1235 & _adc;
 DAC80501 & _dac;
 int _dac_pct;

};

#endif


